// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnfEjpbJTecjjdjUbaVktZSagvVbUB3Xo',
    appId: '1:46413022841:web:9f26bcd2eb43a44d8076a8',
    messagingSenderId: '46413022841',
    projectId: 'examen-dispositivos-66717',
    authDomain: 'examen-dispositivos-66717.firebaseapp.com',
    storageBucket: 'examen-dispositivos-66717.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiEtq_IGqkammt0F1Mwlg2YZIr8tzkF1g',
    appId: '1:46413022841:android:ee475f5833e423098076a8',
    messagingSenderId: '46413022841',
    projectId: 'examen-dispositivos-66717',
    storageBucket: 'examen-dispositivos-66717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACfk3ALKVELLeKcwRHJwlcW8j89oxwFlk',
    appId: '1:46413022841:ios:b6e039d3b5f93d538076a8',
    messagingSenderId: '46413022841',
    projectId: 'examen-dispositivos-66717',
    storageBucket: 'examen-dispositivos-66717.firebasestorage.app',
    iosBundleId: 'com.example.examenDispositivos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACfk3ALKVELLeKcwRHJwlcW8j89oxwFlk',
    appId: '1:46413022841:ios:b6e039d3b5f93d538076a8',
    messagingSenderId: '46413022841',
    projectId: 'examen-dispositivos-66717',
    storageBucket: 'examen-dispositivos-66717.firebasestorage.app',
    iosBundleId: 'com.example.examenDispositivos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnfEjpbJTecjjdjUbaVktZSagvVbUB3Xo',
    appId: '1:46413022841:web:defc5bb27ff02e5f8076a8',
    messagingSenderId: '46413022841',
    projectId: 'examen-dispositivos-66717',
    authDomain: 'examen-dispositivos-66717.firebaseapp.com',
    storageBucket: 'examen-dispositivos-66717.firebasestorage.app',
  );
}
